
# SEO settings
title: "CU "
title2: "Stats" # default: ""
description: "Class statistics for CU Boulder"
keywords: "University, of, Colorado, Boulder, class, statistics, grades"
url: http://nikhilrajaram.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/nikhilrajaram/nikhilrajaram.github.io
#disqus_shortname: "hnbloggithub"
twitter_username: "nikhilrajaram"
comments: true

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nikhil Rajaram"
  job      : "Applied Math/Computer Science student"
  bio      : "Aspiring data scientist || University of Colorado Boulder 2020"
  thumb    : /images/author.jpg
  email    : nikhilrajaram2@gmail.com
  url      : http://nikhilrajaram.github.io
  github   : http://github.com/nikhilrajaram
  twitter  : http://twitter.com/nikhilrajaram
  facebook : https://www.facebook.com/nrajaram2
  instagram: https://www.instagram.com/nikhilrajaram
  linkedin : https://www.linkedin.com/in/nikhilrajaram/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@nikhilrajaram"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
