
# SEO settings
title: "Nikhil"
title2: " Rajaram" # default: ""
description: "University of Colorado Boulder"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://heiswayi.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-101341502-1
repo: http://github.com/nikhilrajaram/nikhilrajaram.github.io
disqus_shortname: ""
twitter_username: "herecomestheraj"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nikhil Rajaram"
  job      : "Applied Math/Computer Science student"
  bio      : "Aspiring data scientist || University of Colorado Boulder 2020"
  thumb    : /images/author.jpg
  email    : nikhilrajaram2@gmail.com
  url      : http://nikhilrajaram.github.io
  github   : http://github.com/nikhilrajaram
  twitter  : http://twitter.com/nikhilrajaram
  facebook : https://www.facebook.com/nrajaram2
  instagram: https://www.instagram.com/nikhilrajaram
  linkedin : https://www.linkedin.com/in/nikhilrajaram/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@herecomestheraj"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
